### ISSUE TITLE
Generate entity names specific to provider or rate plan

### ISSUE THREAD

**Issue by robchandhok** [firstof9/ha-openei#22]
**Is your feature request related to a problem? Please describe.**
First, thank you for releasing and supporting ha-openei!  One minor comment: I think the sensors the integration generates should be named in a less generic fashion.   `binary_sensor.approval` is ambiguous at best. 

**Describe the solution you'd like**
I would suggest either naming the sensors with the electric providers name, such as `binary_sensor.pacific_gas_electric_co_approval`, or some other more appropriate HA convention.

**Describe alternatives you've considered**
I could change each entity name manually, but not sure that scales.

**Additional context**
none

**Comment by firstof9** [comment]
I'll put it on the todo list
