### ISSUE TITLE
Support data from mincharge key in API

### ISSUE THREAD

**Issue by coleya** [firstof9/ha-openei#45]
**Is your feature request related to a problem? Please describe.**
A minimum fee for each month of service is charged by PG&E  leading to the cost sensor being consistently offset from it's true value.

**Describe the solution you'd like**
I think it would be most convenient to detect which of the three possible units ($/day, month, year) are being used through the minchargeunits key and then add the value to the corresponding value sensor when the corresponding energy sensor resets.

**Describe alternatives you've considered**
The simplest version of this I can imagine would give a sensor with the value of mincharge and that has minchargeunits as an attribute. The compensation and detection of when the sensor resets would then be left as an exercise for the user.

**Additional context**
[API reference](https://openei.org/services/doc/rest/util_rates/?version=7)

**Comment by firstof9** [comment]
Please see if 0.1.5-b8 provides the information.

**Comment by coleya** [comment]
I installed it and it reads 10.11 $/month as expected now I just have to figure out how to do the compensation. Thanks for the feature.
