### ISSUE TITLE
[Feat] Filter out old records using the effective as of filter.

### ISSUE THREAD

**Issue by niemyjski** [firstof9/ha-openei#51]
## Version of ha-openei

latest

## Describe the bug
I noticed for Wisconsin Public Service (https://openei.org/apps/USURDB/?utilRateFinder=Wisconsin+Public+Service+Corp&service_type=&effective_date=2021-09-23) I had tons and tons of plans showing with the same name as my plan (https://openei.org/apps/USURDB/rate/view/5c40c3b65457a3a70f1482c5). I had to guess what the sort was in the list. I noticed once I filtered out all the inactive it was much shorter:

![image](https://user-images.githubusercontent.com/1020579/134518215-5cd1c563-6e6a-4bad-b19c-4c8f6c2ba884.png)

**Comment by firstof9** [comment]
Could you see if 0.1.6-b0 does what you're asking?

Thanks.

**Comment by coleya** [comment]
I installed the beta and it hides the tons of old tariffs that appeared before the correct and up to date ones for PG&E.

**Comment by niemyjski** [comment]
Amazing job, that fixed it and it helped me find the correct plan! I did find another issue which I'll post a new issue.
