### ISSUE TITLE
[BUG] - Missing Adjustments $/kWh

### ISSUE THREAD

**Issue by spf13** [firstof9/ha-openei#61]
Using Latest (Head)

This is part bug and part feature request. 

With my utility they split the charges across two fields. The rate field and the adjustment field. 
This library only provides the value of the rate field, which means that it's inaccurate as to the actual charges (rate + adjustment). 

Other applications I've used provide the sum of these two numbers (the actual rate charged). This library ignores the adjustment portion.

**Comment by spf13** [comment]
Adding more context, here's the data sheet from openei for my utility - 
https://apps.openei.org/USURDB/rate/view/62fe87aff6dee418ab7bfcf9#3__Energy

**Comment by firstof9** [comment]
So just so I'm clear, they take your kWh usage for both the rate AND the adjustment and then add them together correct?

**Comment by spf13** [comment]
Yes, that's correct. That's the price we actually pay.

**Comment by firstof9** [comment]
I've added a new sensor in version `0.1.8` for adjustment pricing.
