### ISSUE TITLE
[BUG] Wizard to configure never starts

### ISSUE THREAD

**Issue by Cellivar** [firstof9/ha-openei#71]
## Version of ha-openei
Latest installed through HACS
HA-OpenEI 0.1.10
HA 2023.5.4

## Describe the bug

After installation I attempt to add the component. It opens a pop-up saying the wizard is starting. It never proceeds.

![Screenshot_20230725_022955_Chrome](https://github.com/firstof9/ha-openei/assets/1441553/7ecac949-de8a-4dd6-be2e-140576738413)

## Debug log

There were no errors in the log. I can enable a different level if they will help. It's not clear to me how to set this up for just this component.

**Comment by firstof9** [comment]
I am unable to duplicate your issue, try restarting Home Assistant.

**Comment by Cellivar** [comment]
After doing some unrelated changes to my configuration I tried it again, everything appears to be fine now. No idea what made it work, yesterday I had done several restarts after installing it through HACS. Oh well, thanks for taking a look.
