### ISSUE TITLE
[Feature Request] Fixed Charge not being pulled

### ISSUE THREAD

**Issue by birth23** [firstof9/ha-openei#87]
Fixed charge entity not being pulled.
![Screenshot 2024-12-07 155419](https://github.com/user-attachments/assets/07208771-2b35-48dd-8c1d-afde39abe478)

**Comment by firstof9** [comment]
Can you link me the plan please?

**Comment by birth23** [comment]
https://apps.openei.org/USURDB/rate/view/66905b9123dfda7f4b0d5691#4__Fixed_Charges

**Comment by firstof9** [comment]
Please try the beta: 0.1.18-b0
